stages:
  - iac_validate
  - iac_plan
  - iac_apply



default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init

  cache:
    key: terraform
    paths:
      - .terraform

  
terraform_validate:
  stage: iac_validate
  script:
    - terraform validate -var-file=domain-joshpreston_net.tfvars

  except:
    refs:
      - main


terraform_plan:
  stage: iac_plan
  script: 
    - terraform plan -var-file=domain-joshpreston_net.tfvars --out plan

  artifacts:
    paths:
      - plan


terraform_apply:
  stage: iac_apply
  script:
    - terraform apply --auto-approve plan

  dependencies:
    - terraform_plan

  when: manual
  allow_failure: false

  only:
    refs:
      - main
